eureka:
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/start
server:
  port: 8086
spring:
  application:
    name: service-feign
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
feign:
 hystrix:
  enabled: true