spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-SQL
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mysql.model.User
server:
  port: 8888
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka/
